name: wasm_build

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  ###########################################################
  pre_job:
  ###########################################################
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch"]'

  ###########################################################
  wasm_build:
  ###########################################################
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        target: [linux, darwin, windows]
        architecture: [ 64 ]
        cmake_preset: [ Release ]

        include:
          - target: linux
            runner: ubuntu-latest

          - target: darwin
            runner: macos-latest

          - target: windows
            runner: windows-latest

          - target: windows
            architecture: 64
            architecture_string: x64

    steps:
    - name: "SCM Checkout"
      uses: actions/checkout@v4
      
    - uses: lukka/get-cmake@latest

    - name: "Install: Required Dev Packages"
      run: |
        set -eux
        
        git clone https://github.com/emscripten-core/emsdk.git
        
        case "${{ matrix.target }}${{ matrix.architecture }}" in
          linux64)
            echo "MARCH=64" >> $GITHUB_ENV
            sudo apt-get update -y
            sudo apt-get install --no-install-recommends -y \
              libatomic-ops-dev \
              libglu1-mesa-dev \
              freeglut3-dev \
              mesa-common-dev \
              libglfw3-dev \
              libfreetype6-dev \
              libudev-dev \
              libopenal-dev \
              libvorbis-dev \
              libflac-dev \
              libclang-dev \
              libx11-dev \
              libxrandr-dev \
              libxcursor-dev \
              libxinerama-dev \
              libxi-dev
              
            ./emsdk/emsdk install latest
            ./emsdk/emsdk activate latest
            source "/home/runner/work/daScript/daScript/emsdk/emsdk_env.sh"
            ;;
          windows*)
            ./emsdk/emsdk install latest
            ./emsdk/emsdk activate latest
            ./emsdk/emsdk_env.bat
            ;;
          *)
            ./emsdk/emsdk install latest
            ./emsdk/emsdk activate latest
            source "/Users/runner/work/daScript/daScript/emsdk/emsdk_env.sh"
            ;;
        esac
    - name: "Build: daslang web"
      run: |
        set -eux
        cd web
        cp ../CMakeXxdImpl.txt .
        rm -r -f cmake_temp
        mkdir cmake_temp
        cd cmake_temp
        cmake -DCMAKE_BUILD_TYPE:STRING=${{ matrix.cmake_preset }} -G Ninja -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ../
        ninja
        
    - name: "Deploy: Daslang to try-dascript repo"
      if: github.ref == 'refs/heads/master' && matrix.target == 'darwin' && matrix.architecture == '64' && matrix.cmake_preset == 'Release' && github.event_name != 'pull_request'
      run: |
        set -eux
        # Create temporary directory for cloning target repository
        mkdir -p /tmp/try-dascript
        cd /tmp/try-dascript
        
        # Clone target repository
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://x-access-token:${{ secrets.TRY_DASCRIPT_CONTENT }}@github.com/profelis/try-dascript.git .
        
        # Define the directory where to place wasm file
        TARGET_DIR="." # Change to the path relative to target repository root
        
        # Copy WASM file from the source project
        cp $GITHUB_WORKSPACE/web/output/daScript.wasm $TARGET_DIR/
        cp $GITHUB_WORKSPACE/web/output/daScript.js $TARGET_DIR/
        
        # Check if there are any changes to commit
        if git diff --quiet; then
          echo "No changes detected. Skipping commit and push."
          exit 0
        fi
        
        # Create a new branch
        BRANCH_NAME="update-wasm-$(date +'%Y%m%d-%H%M%S')"
        git checkout -b $BRANCH_NAME
        
        # Add file to index, commit and push
        git add $TARGET_DIR/daScript.wasm
        git add $TARGET_DIR/daScript.js
        git commit -m "Update Daslang from CI build"
        
        # Try to push directly, if not possible create a PR
        if git push origin $BRANCH_NAME; then
          echo "Successfully pushed changes to target repository"
        else
          echo "Creating a pull request instead of direct push"
          # Push changes to new branch
          git push origin $BRANCH_NAME
          
          # Create PR using GitHub API
          PR_BODY="{\"title\":\"Update Daslang from CI build\",\"body\":\"Automatically generated PR with updated Daslang\",\"head\":\"$BRANCH_NAME\",\"base\":\"main\"}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.TRY_DASCRIPT_CONTENT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$PR_BODY" \
            https://api.github.com/repos/profelis/try-dascript/pulls
        fi
